### ISSUE TITLE
There is something not right about changing the experience nugget into liquid experience

### ISSUE THREAD

**Issue by jizaiqwq** [DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric-Legacy#10]
when I use the nugget and stand on the disenchanter,it only produce 3mB liquid experience
![2023-07-07_09 29 14](https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric/assets/87985716/0a935b82-2185-4e05-9874-f3c81465b3e0)
![2023-07-07_09 29 19](https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric/assets/87985716/24e94c7c-9ba4-4048-8e4c-99e4d00b8b38)
but when I change the nugget to liquid experience through the funnel,it produce 729mB

![2023-07-07_09 32 32](https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric/assets/87985716/af1a8d8c-2930-4070-bbed-cafa96d7e500)
![2023-07-07_09 32 38](https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric/assets/87985716/d04be291-71a0-4a71-b731-38509166fd6d)

**Comment by MarbleGateKeeper** [comment]
Your mod version, please?

**Comment by jizaiqwq** [comment]
> Your mod version, please?

fabric create 0.5.1b,create_enchantment_industry beta 0.1.8
