### ISSUE TITLE
Game crashes when pondering with ColorfulEnchantments

### ISSUE THREAD

**Issue by LizzieSpace** [DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric-Legacy#11]
[ColorfulEnchantments](https://www.curseforge.com/minecraft/mc-mods/colorful-enchantments) causes the game to crash whenever an enchantment book appears during a ponder render.

[Logs related to the issue](https://mclo.gs/zEAh2er)

To reproduce
start game with ColorfulEnchantments and ponder the enchanting guide

Am not sure if it's related to the Enchantment Industry or if it's about how ponder renders items, but I've got a gut feeling it is about how create collects models for rendering. The game crashes when using the creative world shaper to get a grass block while having lambaBetterGrass.

I've taken initiative and reported it to the Create Fabric page.
https://github.com/Fabricators-of-Create/Create/issues/1011

**Comment by MarbleGateKeeper** [comment]
I've read the log, and I think it should be reported to [ColorfulEnchantments](https://www.curseforge.com/minecraft/mc-mods/colorful-enchantments).
