### ISSUE TITLE
1.20.1

### ISSUE THREAD

**Issue by Deep-Shift** [DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric-Legacy#12]
### Describe the your request

is a 1.**20.1** update being worked on?

**Comment by MarbleGateKeeper** [comment]
1.20.1 will come later. Kinda busy these days.

**Comment by liamwerk7676** [comment]
when are you done with the 1.20.1 update

**Comment by DefomCode** [comment]
we have been waiting for more than a month...

**Comment by adaliszk** [comment]
If you want to help with the upgrade, you can always contribute. The maintainers are active on the [1.20.1/0.5.1-dev](https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric/tree/1.20.1/0.5.1-dev) branch; you can probably clone it to build and test for issues.

**Comment by DefomCode** [comment]
When will there be an update to 1.20.1 version? there has been nothing for almost 2 months

**Comment by Br31zh** [comment]
Do you realize how disrespectful it is to be so demanding of volunteers who offer the result of their work for free and owe you nothing? Be patient. Or do it yourself.

(PS. I'm sorry if this is an inappropriate reaction as a third party, but I really don't like this behavior)

**Comment by liamwerk7676** [comment]
how far is the progress on the 1.20.1 port ?

> If you want to help with the upgrade, you can always contribute. The maintainers are active on the [1.20.1/0.5.1-dev](https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric/tree/1.20.1/0.5.1-dev) branch; you can probably clone it to build and test for issues.

**Comment by ST-DDT** [comment]
Are there any particular things I can help with?
