### ISSUE TITLE
sweep edge disable in deployer

### ISSUE THREAD

**Issue by DaliBerr** [DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric-Legacy#14]
### Minecraft Version

1.19.2

### Describe the Bug

When a deployer with sweep edge, it can not work as want. 

### Reproduction Steps

1. 
2.
3.
...

### Expected Result

sweep edge works properly.

### Screenshots and Videos

A test video : https://b23.tv/X1avrwt

### Crash Report or Log

https://gist.github.com/DaliBerr/0f992f35633764f96e33e54fc0374ab5

### Other Mods

![image](https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric/assets/68154963/be0d89d9-36ca-4a11-afa0-678f24ef44de)
![image](https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric/assets/68154963/f5b97422-8b4c-4016-9313-cd93176491d3)
![image](https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric/assets/68154963/2a5608cf-cfc4-4328-b907-1beb40e3881c)
![image](https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric/assets/68154963/b92b461c-d5de-46c2-8a1e-ba6d8b35a09d)

### Mod Version

1.0.1

**Comment by MarbleGateKeeper** [comment]
It should caused by mixin conflict. New fix should work.

**Comment by jonathansharpe** [comment]
I updated to 1.0.1.b, and the bug is still present
