### ISSUE TITLE
I updated to 1.0.1.b, and the bug is still present

### ISSUE THREAD

**Issue by DaliBerr** [DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric-Legacy#15]
I updated to 1.0.1.b, and the bug is still present

_Originally posted by @jonathansharpe in https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric/issues/14#issuecomment-1734862609_

**Comment by spectrapulse** [comment]
> ```
>           I updated to 1.0.1.b, and the bug is still present
> ```
> 
> _Originally posted by @jonathansharpe in [#14 (comment)](https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric/issues/14#issuecomment-1734862609)_

Don't make duplicate issues. Just ask in the original issue if it can be reopened, additionally "I updated to 1.0.1.b, and the bug is still present" is not a very descriptive nor helpful topic.
