### ISSUE TITLE
Crash on startup with Quilt

### ISSUE THREAD

**Issue by JLUsr** [DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric-Legacy#2]
Minecraft 1.19.2
Quilt 0.19.1
Create 0.5.1-b-build.1079
create_enchantment_industry-beta-0.1.3 (I also tried 0.1.2 and 0.1.1 and had the same results)

See this [gist](https://gist.github.com/JLUsr/0ac068d878643393a34c450908b3ac05) for what happens when starting a quilt server whilst Enchantment Industry is present.

**Comment by MarbleGateKeeper** [comment]
Please give it a retry and it might work.
I haven't figure out how to fix this bug yet. It's so unstable & rare to reproduce in fabric.

**Comment by JLUsr** [comment]
I gave it a few more attempts to verify and can confirm the [log](https://gist.github.com/JLUsr/c2a29d562d993a9150ab4b58a3f57dd1) remains the same. I attempted to use the Quilt-specific version as per curseforge (0.1.1) as well as the version listed as supported for Fabric and Quilt on Modrinth (0.1.3). I do have other mods present so I'll spend some time testing a server without the extra variables and provide an additional gist if needed. I can also confirm that this is a server-only issue.

**Comment by MarbleGateKeeper** [comment]
Please provide extra gist, really appreciated for it and also extra tests.

I'll test it tomorrow.

**Comment by JLUsr** [comment]
So, it turns out that NotEnoughCrashes was letting my client start but the mod was not actually loading. Here is the updated [gist](https://gist.github.com/JLUsr/8bab29cafaa73fb1e894d8a0812752cb) from both the server and the client. They are only running with the required mods installed.

**Comment by MarbleGateKeeper** [comment]
Could you try beta-0.1.4?

**Comment by JLUsr** [comment]
Confirmed that beta-0.1.4 resolved this issue.

**Comment by MarbleGateKeeper** [comment]
Ah! A problem of accidentally triggering class loading too early.
