### ISSUE TITLE
[1.20.1] [Quilt] Crash on Startup

### ISSUE THREAD

**Issue by noawx** [DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric-Legacy#29]
### Minecraft Version

1.20.1

### Describe the Bug

The game starts on startup.

### Reproduction Steps

1. Have the selected mods enabled
2. Start the game
3. Error occurs
...

### Expected Result

Game boots up and doesn't crash

### Crash Report or Log

https://mclo.gs/lpMB5Fs

### Mod Version

1.0.1

**Comment by IThundxr** [comment]
Seems like a qsl/qfapi issue or a registrate fabric issue, report to them

**Comment by IThundxr** [comment]
actually, try 1.2.8

**Comment by spacky1** [comment]
Latest version still crashes on Quilt for me as well.

**Comment by IThundxr** [comment]
> Latest version still crashes on Quilt for me as well.

Send a log

**Comment by spacky1** [comment]
Here's a log with just Create + Enchantment Industry and QFAPI:
https://paste.ee/p/Ql4wN

**Comment by liamwerk7676** [comment]
i have the same isue fist i thought it was a isue with https://modrinth.com/mod/create-fabric-sodium-fix but now im sure its quilt im going to try stitching to fabric now

**Comment by liamwerk7676** [comment]
yes its incompatible with quilt with fabric it works fine

**Comment by NolanHewitt** [comment]
Same issue here. Is this something that needs quilt to update to the newer fabric api, or something this mod has to fix to solve?

**Comment by IThundxr** [comment]
> Same issue here. Is this something that needs quilt to update to the newer fabric api, or something this mod has to fix to solve?

It's something between qfapi/qsl & registrate

**Comment by liamwerk7676** [comment]
> > Same issue here. Is this something that needs quilt to update to the newer fabric api, or something this mod has to fix to solve?
> 
> It's something between qfapi/qsl & registrate

im going to try and work on a unoficial fix until it gets fixed in the mean time just switch to fabric and disable any quilt mods

nvm i dont know how to code so just switch to fabric until its fixed

**Comment by TropheusJ** [comment]
This is not an issue with Quilt. CEI is relying on mod load order. This only works on Fabric with pure luck.
<https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric/blob/772bedc9f56671656087ccbd992c379e1199a1ad/src/main/java/plus/dragons/createenchantmentindustry/foundation/mixin/AbstractFurnaceBlockEntityMixin.java#L49>
if AbstractFurnaceBlockEntity is loaded before CEI registers fluids, this will crash. getSource will get an empty fluid, as it has not been registered yet.
Quilt ends up triggering this condition with the item content registries initializer.

**Comment by IThundxr** [comment]
> This is not an issue with Quilt. CEI is relying on mod load order. This only works on Fabric with pure luck.
> 
> https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric/blob/772bedc9f56671656087ccbd992c379e1199a1ad/src/main/java/plus/dragons/createenchantmentindustry/foundation/mixin/AbstractFurnaceBlockEntityMixin.java#L49
> 
> 
> if AbstractFurnaceBlockEntity is loaded before CEI registers fluids, this will crash. getSource will get an empty fluid, as it has not been registered yet.
> Quilt ends up triggering this condition with the item content registries initializer.

Would just removing the field and creating the fluid variant where it's needed fix this?

**Comment by TropheusJ** [comment]
yes

**Comment by IThundxr** [comment]
Fixed in latest (1.2.10)
