### ISSUE TITLE
[1.20.1] [Fabric] Crash on startup

### ISSUE THREAD

**Issue by sizoroot** [DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric-Legacy#30]
### Minecraft Version

1.19.2

### Describe the Bug

Server (and game) crash on startup

### Reproduction Steps

1. Start the server
2. Server crash

### Expected Result

Server startup and work

### Crash Report or Log

https://pastebin.com/JatFBpYu

### Other Mods

athena_3.0.0.jar
audioplayer_1.8.5.jar
banner_496.jar
beautify_1.1.0.jar
better_archeology_1.1.0.jar
better_end_4.0.10.jar
better_nether_9.0.9.jar
concurrent_chunk_management_engine_0.2.0_0.2.0.jar
cc_tweaked_1.109.0.jar
chipped_3.0.1.jar
choice_theorems_overhauled_village_3.3.6.jar
clumps_12.0.0.3.jar
cobblemon_1.4.0.jar
cobblemon_capturexp_1.4.jar
connectible_chains_2.2.1.jar
create_0.5.1d.jar
create_addition_0.9.0.jar
create_air_1.0.jar
create_bells_and_whistles_0.4.5.jar
create_disel_generators_2.1.3.jar
create_enchantment_industry-1.2.7.jar
create_jetpack_4.0.0.jar
create_rechiseled_1.0.1.jar
create_slice_and_dice_3.0.0.jar
create_steam_and_rails_1.5.1.jar
create_utilities_0.1.3b.jar
creeper_overhaul_3.0.1.jar
croptopia_2.3.2.jar
ctov_farmers_delight_compat_2.1.jar
delightful_creators_1.1.8.jar
easy_shulker_boxes_8.0.0.jar
enderman_overhaul_1.0.3.jar
ends_delight_1.0.1.jar
experience_bottler_build.2.jar
falling_tree_4.3.1.jar
farmers_delight_1.4.2.jar
ferritecore_6.0.1.jar
forgotten_graves_3.2.5.jar
handcrafted_3.0.5.jar
immersive_aircraft_0.6.2.jar
immersive_armors_1.6.1.jar
ironchests_5.0.2.jar
lib_balm_7.0.7.jar
lib_bclib_3.0.13.jar
lib_botarium_2.1.2.jar
lib_cloth_config_11.1.106.jar
lib_collective_7.9.jar
lib_cristellib_1.1.5.jar
lib_fabric_api_0.88.1.jar
lib_fabric_language_kotlin_1.10.15.jar
lib_forge_config_api_port_8.0.0_required.jar
lib_forge_config_api_port_8.0.0.jar
lib_framework_0.6.16.jar
lib_fusion_1.1.0c.jar
lib_geckolib_4.2.3.jar
lib_lithium_0.11.2.jar
lib_moonlight_2.8.66.jar
lib_owo_lib_0.11.2.jar
lib_patchouli_83.jar
lib_puzzleslib_8.1.9.jar
lib_resourcefulconfig_2.1.0.jar
lib_resourcefullib_2.1.18.jar
lib_starlight_156f.jar
lib_supermartijn642configlib_1.1.8a.jar
lib_supermartijn642corelib_1.1.15.jar
lib_yungs_api_4.0.2.jar
mcw_fences_1.0.7.jar
mighty_mail_1.0.14.jar
more_mob_variants_1.2.2.jar
more_villagers_5.0.0.jar
moving_elevators_1.4.3a.jar
nether_portal_fix_13.0.0.jar
nethers_delight_1.0.0.jar
paragliders_20.1.1.jar
rechiseled_1.1.5b.jar
snowy_spirit_2.2.6.jar
starterkit_5.3.jar
supplementaries_2.6.34.jar
terralith_2.4.8.jar
trinkets_3.7.1.jar
voicechat_2.4.28.jar
worldedit_7.2.15.jar
wraith_waystones_3.3.1.jar
wunderreich_6.0.4.jar
yawp_0.0.2.9_b3.jar
yungs_better_dungeons_4.0.3.jar
yungs_better_mineshafts_4.0.4.jar
yungs_better_ocean_monuments_3.0.4.jar
yungs_better_strong_holds_4.0.3.jar

### Mod Version

CEI 1.2.7 for Create 1.20.1-0.5.1-d-build.1161+mc1.20.1

**Comment by IThundxr** [comment]
Could you send a full log?

**Comment by IThundxr** [comment]
fixed in 1.2.8
