### ISSUE TITLE
Selecting an enchantment book in the last inventory row drops the item

### ISSUE THREAD

**Issue by ST-DDT** [DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric-Legacy#32]
### Minecraft Version

1.20.1

### Describe the Bug

I cannot select an enchantment book in the last inventory row when the enchantment guide is open.

Also the selected enchantment text floats at the cursor and is not in the selection window.

### Reproduction Steps

1. Open the enchantment guide
2. Put the enchantment book anywhere in the first 8 rows
3. Left click the book to pick it up ✔
4. Put it anywhere in the 9th row
5. Left click the book to pick it up ⚠️
6. The item is dropped on the floor immediately

### Expected Result

The book is picked up to the cursor.

### Screenshots and Videos

![grafik](https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric/assets/1579362/1cc9c0d8-e28c-45b0-a347-a72b3a8c6ccf)

[screen-recorder-sat-dec-02-2023-11-15-53.webm](https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric/assets/1579362/ae6af935-1caf-498a-a217-69b5d339a1df)

### Other Mods

- create_enchantment_industry-1.2.9.jar
- create-fabric-0.5.1-d-build.1161+mc1.20.1.jar
- fabric-api-0.88.1+1.20.1.jar

### Mod Version

1.2.9

**Comment by DefomCode** [comment]
same
