### ISSUE TITLE
Printer can't take liquids

### ISSUE THREAD

**Issue by DefomCode** [DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric-Legacy#34]
### Minecraft Version

1.20.1

### Describe the Bug

Printer can't take liquids. If you try to pour liquid with a pump (ink, liquid experience or hyper experience), then nothing will work. Because of this, this block literally loses its functionality.
![Скриншот 05-12-2023 013812](https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric/assets/91155582/3c0d61f2-a0fe-43e3-bc39-95ef539eac4e)

### Reproduction Steps

1. try to power liquid with a pump
2. It doesn't work out

### Expected Result

printer is filled with liquids (ink experience and hyper experience) 

### Other Mods

* Fabric API
* Cloth Config API
* Fabric Language Kotlin
* Architectury API
* Sodium
* Create Fabric Sodium Fix
* Create Crafts & Additions
* CreateFabric&REIBugFix
* Create: Steam 'n' Rails
* Create: New Age
* Create mod Trims
* Create Jetpack
* Create: Broken Bad
* Emotecraft
* Roughly Enough Items (REI)
* No Chat Reports
* Carry On
* Botarium
* Artifacts

### Mod Version

1.2.9

**Comment by IThundxr** [comment]
Could you try using a pipe as a buffer between the pump and the printer?

**Comment by IThundxr** [comment]
Fixed in latest release (1.2.10)
