### ISSUE TITLE
Crash on Startup [quilt 1.20.1]

### ISSUE THREAD

**Issue by NolanHewitt** [DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric-Legacy#35]
### Minecraft Version

1.20.1

### Describe the Bug

Crashes on start up. Tested using only Create, Create Enhchantment Industry, quilted fabric API, and Sodium.

Tested both normal create with sodium 4, and the create sodium fix version with sodium 5. Both crash.

### Reproduction Steps

Start game with mod on quilt, game crashes

### Expected Result

Game doesn't crash

### Crash Report or Log

https://gist.github.com/NolanHewitt/c17349cc3b8802f2b196cc9d1caddc7a

### Other Mods

Tested using only the required mods and sodium.

### Mod Version

1.2.9

**Comment by IThundxr** [comment]
#29
