### ISSUE TITLE
Blaze Enchanter doesn't work

### ISSUE THREAD

**Issue by bit69tream** [DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric-Legacy#4]
Version: `beta-0.1.5`

This is what I'm getting in my survival world:

![изображение](https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric/assets/43259894/06a1493e-0804-458f-a516-b3292e687f8c)

And this is what I get in creative mode:

![изображение](https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric/assets/43259894/2c8d43bb-e2da-4e0e-92a9-e80e586183d5)

**Comment by MarbleGateKeeper** [comment]
Thanks for reporting.

I have a flight to another city this morning for my brother's graduation and my aunt's birthday, and there will be no updates or fixes until the 28th. Sorry for inconvenience.
