### ISSUE TITLE
[Quilt 1.20.1] Crash on startup

### ISSUE THREAD

**Issue by Hippopipo** [DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric-Legacy#42]
### Minecraft Version

1.20.1

### Describe the Bug

Game crashes on startup, updated to latest version

### Reproduction Steps

1. Start game
2. Crash

### Expected Result

No crash

### Crash Report or Log

https://mclo.gs/QNtN8g3

### Other Mods

Too lazy to list them all so just look at the log

### Mod Version

1.2.12

**Comment by IThundxr** [comment]
Remove extended cogwheels

**Comment by IThundxr** [comment]
Actually wait no

**Comment by IThundxr** [comment]
moreculling Remove it
