### ISSUE TITLE
Nugget of experience can't be used by disenchanter

### ISSUE THREAD

**Issue by meishiffx** [DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric-Legacy#43]
### Minecraft Version

1.20.1

### Describe the Bug

Nugget of experience can't be used by disenchanter.There is no need to change in the ponder interface.

### Reproduction Steps

Enter disenchanter into Nugget of experience.

### Expected Result

Nugget of experience is consumed.

### Mod Version

1.2.12

**Comment by ColinEspinas** [comment]
It seems that this is not fixed?

![Image](https://github.com/user-attachments/assets/d1710e11-db9d-4e11-ab04-04ff69863cca)

Have a good day.
