### ISSUE TITLE
Game Crash after Deployer Killed an entity

### ISSUE THREAD

**Issue by SpiderKolo** [DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric-Legacy#45]
### Minecraft Version

1.20.1

### Describe the Bug

Whenever a Deployer kills a mob, game crashes immediately after.

### Reproduction Steps

1. Set-up a Deployer in a punching/mining mode targeting space that target can't escape.
2. Put a mob in that space.
3. Let Deployer deal with the target.

After third step is done, the game crashes.

### Expected Result

Deployer collects items and nugget of experience to it's inventory which then would need to be pulled out of the Deployer.

### Crash Report or Log

https://pastebin.com/V3BRhseu

### Other Mods

While no other mods than **Create Fabric** and **Create Enchantment Industry Fabric** were actively used in experiment, this is the whole list of mods that was present at the time of the last crash.

Mods:
  [✔️] AdaptiveTooltips-1.3.0-fabric-1.20.2.jar
  [✔️] Amplified_Nether_1.20.2_v1.2.3.jar
  [✔️] appleskin-fabric-mc1.20.1-2.5.1.jar
  [✔️] architectury-9.1.12-fabric.jar
  [✔️] autoslabs-1.1.3.jar
  [✔️] AxesAreWeapons-1.7.1-fabric-1.19.3.jar
  [✔️] Axiom-1.5.1-for-MC1.20.1.jar
  [✔️] bedrock-bone-meal-1.2.0+1.20.jar
  [✔️] benchantments-v1.0.1.jar
  [✔️] biomemakeover-FABRIC-1.20.1-1.11.4.jar
  [✔️] Bookshelf-Fabric-1.20.1-20.1.6.jar
  [✔️] Bovines-And-Buttercups-Fabric-1.9.0+1.20.1.jar
  [✔️] BridgingMod-2.2.1+1.20.1.fabric-release.jar
  [✔️] cccbridge-mc1.20.1-fabric-v1.6.2b.jar
  [✔️] cc-tweaked-1.20.1-fabric-1.108.4.jar
  [✔️] chalk-2.2.0.jar
  [✔️] chalk-colorful-addon-2.1.1.jar
  [✔️] chat_heads-0.10.22-fabric-1.20.jar
  [✔️] cherry-villages-1.0.3.jar
  [✔️] CIA-1.1.0-Fabric-MC1.20.1.jar
  [✔️] cinderscapes-4.0.8.jar
  [✔️] cloth-config-11.1.106-fabric.jar
  [✔️] continuity-3.0.0-beta.4+1.20.1.jar
  [✔️] create_enchantment_industry-1.2.12.jar
  [✔️] create-fabric-0.5.1-d-build.1161+mc1.20.1.jar
  [✔️] create-origins-v1.2.1-fabric-quilt+1.20.1.jar
  [✔️] CullLessLeaves-1.3.0.jar
  [✔️] dawn-5.0.0.jar
  [✔️] delightful-creators-1.1.8.jar
  [✔️] dualwielding-1.1.2.jar
  [✔️] ecologics-fabric-1.20.1-2.2.0.jar
  [✔️] economical-villager-trading-1.2.10+MC1.20-1.20.1.jar
  [✔️] EnchantmentDescriptions-Fabric-1.20.1-17.0.8.jar
  [✔️] enchanttweaker-1.4.5+mc1.20-1.20.1.jar
  [✔️] entityculling-fabric-1.6.2-mc1.20.1.jar
  [✔️] extraalchemy-fabric-1.20.1-1.10.0.jar
  [✔️] fabric-api-0.91.1+1.20.1.jar
  [✔️] farmers-delight-fabric-mc1.20.1-1.4.2.jar
  [✔️] flatbedrock-fabric-3.0.1-build.18+mc1.20.1.jar
  [✔️] fluidlogged-2.0.1-beta.2-fabric-mc1.20.1.jar
  [✔️] flynt1.0.4.jar
  [✔️] gardens-of-the-dead-fabric-4.0.1.jar
  [✔️] global_packs-fabric-1.19.4-1.16.1_fabric.jar
  [✔️] map-atlases-2.6.0+1.20.1.jar
  [✔️] MissingWilds-fabric-1.2.0+1.20.1.jar
  [✔️] modmenu-7.2.2.jar
  [✔️] moonlight-1.20-2.8.56-fabric.jar
  [✔️] more_armor_trims-fabric-1.20.1-1.1.3.jar
  [✔️] morepumpkins-1.20.1-1.0.0.jar
  [✔️] Necronomicon-Fabric-1.4.2.jar
  [✔️] nerb-1.20.1-0.3-FABRIC.jar
  [✔️] NetherChested-v8.0.1-1.20.1-Fabric.jar
  [✔️] NoChatReports-FABRIC-1.20.1-v2.2.2.jar
  [✔️] notenoughanimations-fabric-1.6.4-mc1.20.jar
  [✔️] obtainable-end-1.0.3.jar
  [✔️] Origins-1.20.1-1.10.0.jar
  [✔️] owo-lib-0.11.2+1.20.jar
  [✔️] Pehkui-3.7.11+1.14.4-1.20.2.jar
  [✔️] player-animation-lib-fabric-1.0.2-rc1+1.20.jar
  [✔️] pocketwatch-1.1.1+1.20.jar
  [✔️] projectile_damage-fabric-3.2.2+1.20.1.jar
  [✔️] PuzzlesLib-v8.1.5-1.20.1-Fabric.jar
  [✔️] rer-2.9.0.jar
  [✔️] RoughlyEnoughItems-12.0.684-fabric.jar
  [✔️] ruined-equipment-2.3.1+1.20.1.jar
  [✔️] screenshot_viewer-1.2.1-fabric-mc1.20.jar
  [✔️] simpletrims-0.2.0.jar
  [✔️] smarterfarmers-1.20-1.7.3-fabric.jar
  [✔️] spawn-1.0.3-fabric.jar
  [✔️] spellbound-1.15.0.1.jar
  [✔️] Steam_Rails-1.5.1+fabric-mc1.20.1.jar
  [✔️] suggestion-tweaker-1.20-1.5.1-fabric.jar
  [✔️] TooManyOrigins-1.0.0-beta.19+1.20.1-fabric.jar
  [✔️] traverse-7.0.9.jar
  [✔️] vectorientation-1.0.1a-1.20.jar
  [✔️] villager-trading-station-1.2.0.jar
  [✔️] visuality-0.7.1+1.20.jar
  [✔️] water-resistance-potion-1.1.0+1.20.1.jar
  [✔️] whokilledtheenderdragon-1.0.0-1.20.1.jar
  [✔️] WitherTurnsSkeletons-1.2.0+1.20.jar
  [✔️] yet-another-config-lib-fabric-3.2.1+1.20.jar
  [✔️] youaremypoison-1.0.1-1.20.1-fabric.jar

### Mod Version

Create: Enchantment Industry 1.2.12 (which happened to be newest version at the time of writing this report)

**Comment by IThundxr** [comment]
Create issue.
