### ISSUE TITLE
The printer uses too little Liquid Experience

### ISSUE THREAD

**Issue by bit69tream** [DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric-Legacy#5]
Version: `beta-0.1.5`

![ezgif-2-87c9e2dce7](https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric/assets/43259894/1bdd1eee-28ec-4a26-9011-f55b26be94a3)

It says that it would consume 102mB, but it actually consumes a tiny bit more than 1mB.

**Comment by MarbleGateKeeper** [comment]
A forge->fabric fluid unit transition problem. Thanks for reporting.
