### ISSUE TITLE
[ISSUE] Windows Defender flags this mod as a Trojan when downloaded from Modrinth.

### ISSUE THREAD

**Issue by Clark919** [DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric-Legacy#51]
### Minecraft Version

1.20.1

### Describe the Bug

As the title suggests, downloading this mod from Modrinth will flag the following as a Trojan on Windows Defender:
```
Trojan:Script/Wacatac.B!ml
```
It's associated with just this .jar file for Fabric 1.20.1 onwards. Could be a false flag but either way it would be nice to download the mod and not have to be concerned about potential malware. I downloaded several other mods at the same time and this is the only one that has had this issue.

### Reproduction Steps

1. Download the mod from [Modrinth](https://modrinth.com/mod/create-enchantment-industry-fabric/versions) (specifically I tried versions 1.2.16 and 1.2.12).
2. Windows Defender automatically scans the .jar file and flags it as a Trojan.
...

### Expected Result

Expected behaviour is to not have a malware warning while downloading the mod.

### Screenshots and Videos

N/A

### Crash Report or Log

N/A

### Other Mods

N/A

### Mod Version

1.2.16/1.2.12

**Comment by IThundxr** [comment]
False positive, The code's open source and we build it on github actions just to be sure theres no tampering of the jar during upload. https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric/actions/runs/8217147387/job/22472526425 heres the logs for the release i guess you can just ignore it, probably some hash collision or something
