### ISSUE TITLE
Client crash on 1.20.1 with Create 0.5.1-f-build.1335

### ISSUE THREAD

**Issue by KubLuk24** [DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric-Legacy#59]
### Minecraft Version

1.20.1

### Describe the Bug

The mod prevents the client from loading by crashing the entire game on startup

### Reproduction Steps

1. Install any version of the mod compatible with Create 0.5.1-F Build 1335 (aka version 1.2.15 or 1.2.16)
2. Run the client (I am using Technic launcher with console enabled)

### Expected Result

The game should load as there are no other requirements listed for the mod

### Crash Report or Log

https://cdn.mdplx.link/07-04-24_18-43_Ib3YxfFz5a.txt

### Other Mods

		ad_astra: Ad Astra 1.15.18
		advancementinfo: AdvancementInfo 1.20-fabric0.83.0-1.4
		animatica: Animatica 0.6+1.20
		architectury: Architectury 9.2.14
		bclib: BCLib 3.0.14
		bellsandwhistles: Create: Bells & Whistles 0.4.5
		betterend: Better End 4.0.11
		bettermounthud: Better Mount HUD 1.2.2
		betternether: Better Nether 9.0.10
		bigcontraptions: Create: Big Contraptions 1.0
		borderlessmining: Borderless Mining 1.1.8+1.20.1
		botarium: Botarium 2.3.3
		capes: Capes 1.5.2+1.20
		citresewn: CIT Resewn 1.1.3+1.20
		cloth-config: Cloth Config v11 11.1.106
		continuity: Continuity 3.0.0-beta.4+1.20.1
		controlify: Controlify 1.6.0+1.20
		create: Create 0.5.1-f-build.1335+mc1.20.1
		create-track-map: Create Track Map 1.4
		create_bic_bit: Create: Bitterballen 0.0.69C+1.20.1
		create_enchantment_industry: Create Enchantment Industry 1.2.15
		create_interactive: Create: Interactive 1.0.2-beta.1
		create_jetpack: Create Jetpack 4.2.0
		create_new_age: Create: New Age 1.1.2
		create_power_loader: Create: Power Loader 1.4.3-mc1.20.1-fabric
		create_structures: Create: Structures 1.1.0
		createaddition: Create Crafts & Additions 1.2.3
		createbigcannons: Create Big Cannons 0.5.3.b-nightly-8a45d8e
		createdeco: Create Deco 2.0.1-1.20.1-fabric
		createdieselgenerators: Create Diesel Generators 1.2.3h
		creategoggles: Create Goggles 0.5.5.g
		createoreexcavation: Create Ore Excavation 1.4.5
		createorigins: Create: Origins 1.2.1+1.20.1
		createutilities: Create Utilities 0.3.0+1.20.1
		debugify: Debugify 1.20.1+2.0
		distanthorizons: Distant Horizons 2.0.1-a
		dynamic_fps: Dynamic FPS 3.2.1
		e4mc_minecraft: e4mc 4.0.1
		enhancedblockentities: Enhanced Block Entities 0.9+1.20
		entity_model_features: Entity Model Features 1.0.2
		entity_texture_features: Entity Texture Features 4.5.1
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20.1
		extendedgears: Extended Cogwheels 2.1.1-1.20.1-0.5.1.f-fabric
		fabric-api: Fabric API 0.92.0+1.20.1
		fabric-language-kotlin: Fabric Language Kotlin 1.10.10+kotlin.1.9.10
		fabricloader: Fabric Loader 0.15.9
		fabricskyboxes: FabricSkyBoxes 0.7.3+mc1.20.1
		fabrishot: Fabrishot 1.10.0
		fadeless: Fadeless 1.0.1
		fastquit: FastQuit 3.0.0+1.20+
		ferritecore: FerriteCore 6.0.0
		fsb-interop: FabricSkyBoxes Interop 1.3.6+mc1.20.1-build.50
		garnished: Create: Garnished 1.7.5+1.20.1
		immediatelyfast: ImmediatelyFast 1.2.6+1.20.2
		indium: Indium 1.0.30+mc1.20.4
		iris: Iris 1.6.17
		isxander-main-menu-credits: Main Menu Credits 1.1.2
		java: OpenJDK 64-Bit Server VM 17
		lambdynlights: LambDynamicLights 2.3.2+1.20.1
		languagereload: Language Reload 1.5.9+1.20.1
		lithium: Lithium 0.11.2
		memoryleakfix: Memory Leak Fix 1.1.2
		minecraft: Minecraft 1.20.1
		mixintrace: MixinTrace 1.1.1+1.17
		modelfix: Model Gap Fix 1.14
		modernfix: ModernFix 5.8.1+mc1.20.1
		modmenu: Mod Menu 7.2.2
		morechathistory: MoreChatHistory 1.1.1
		moreculling: More Culling 1.20.1-0.19.0
		nochatreports: No Chat Reports 1.20.1-v2.2.2
		opaccreatesupport: OPAC Create Mod Support 1.5.0
		openpartiesandclaims: Open Parties and Claims 0.22.0
		optigui: OptiGUI 2.1.5
		origins: Origins 1.10.0
		origins-classes: Origins: Classes 1.7.0
		puzzle: Puzzle 1.5.2+1.20
		railways: Create: Steam 'n' Rails 1.5.3+fabric-mc1.20.1
		reeses-sodium-options: Reese's Sodium Options 1.7.2+mc1.20.1-build.101
		resourcefulconfig: Resourcefulconfig 2.1.2
		resourcefullib: Resourceful Lib 2.1.24
		rrls: Remove Reloading Screen 3.2.0-1.20.1-fabric
		simplemod: SimpleMod 1.20.1
		sliceanddice: Create Slice & Dice 3.1.0
		sodium: Sodium 0.5.8+mc1.20.1
		sodium-extra: Sodium Extra 0.5.4+mc1.20.1-build.115
		valkyrienskies: Valkyrien Skies 2 2.3.0-beta.5
		wunderreich: Wunderreich 6.0.4
		yet_another_config_lib_v3: YetAnotherConfigLib 3.2.1+1.20
		yosbr: YOSBR 0.1.2
		zoomify: Zoomify 2.11.2

### Mod Version

1.2.16

**Comment by IThundxr** [comment]
opaccreatesupport is crashing
