### ISSUE TITLE
Game not booting when trying to load ver farbic 1.0.1.b

### ISSUE THREAD

**Issue by BonnieSUTF84** [DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric-Legacy#62]
### Minecraft Version

1.19.2

### Describe the Bug

the game wont start 

### Reproduction Steps

The game won't boot when it have the mod in, else work normally

### Expected Result

game supposed to boot :sad

### Crash Report or Log

https://pastebin.com/e2SyYKj1

### Other Mods

![image](https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric/assets/167237292/5d3e5f1e-1ce5-4e9f-9edf-0d9dffc04a12)

### Mod Version

1.0.1.b

**Comment by OlHonder** [comment]
and the fix was?
