### ISSUE TITLE
[BUG] Seems Blaze Enchanter can't accept the experience fluid.

### ISSUE THREAD

**Issue by LittleCircleOO** [DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric-Legacy#66]
### Minecraft Version

1.20.1

### Describe the Bug

With only *create enchantment industry* and *create fabric* installed, attempting to transfer experience fluid from the tank with experience fluid to the blaze enchanter does not result in any response.

### Reproduction Steps

1. Place a fluid tank and a blaze burner.
2. Converting it to blaze enchanter using the enchanting guide.
3. Connecting the two with a pump.
4. Seems Blaze Enchanter can't accept the experience fluid.

### Expected Result

Blaze Enchanter can accept the experience fluid.

### Screenshots and Videos

![Issue](https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric/assets/51949761/db7432a1-3ee6-4953-b1cc-fbf79fded631)

### Other Mods

create-fabric-0.5.1-f-build.1417+mc1.20.1
fabric-api-0.92.1+1.20.1

### Mod Version

1.2.16

**Comment by Karotte128** [comment]
Try attaching the pipe from the bottom of the Blaze Enchanter.

**Comment by LittleCircleOO** [comment]
Oh, that might be a feature, thanks.
