### ISSUE TITLE
Incorrect Blaze Enchanter capacity on a server

### ISSUE THREAD

**Issue by bit69tream** [DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric-Legacy#7]
Version: `0.1.6`

![image](https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric/assets/43259894/7a04fa64-e42a-465b-99d0-0ff74ed5ff10)
On a paper server with a friend Blaze Enchanter has a 2mB capacity, while in singleplayer it has 2B capacity.

**Comment by MarbleGateKeeper** [comment]
Delete server config and let it regenerate. Then place blaze enchanter again.
