### ISSUE TITLE
Game crash using Quilt 1.19.2

### ISSUE THREAD

**Issue by ninjaguardian** [DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric-Legacy#72]
### Minecraft Version

Quilt **1.19.2** 0.26.4-beta.5

### Describe the Bug

The main error seems to be
```shell
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'create_enchantment_industry' at ''!
```

<details>
<summary>

### Reproduction Steps

</summary>

1) Install Quilt 1.19.2 0.26.4-beta.5
2) Install the mods listed bellow
3) Run the game
</details>

### Expected Result

The game should not crash.

### Crash Report or Log

https://mclo.gs/U0yM0zl

<details>
<summary>

### Mods

</summary>

- Create Enchantment Industry - 1.0.1.b
- Create Fabric - 0.5.1-f-build.1416+mc1.19.2
- QFAPI/QSL - 4.0.0-beta.30+0.77.0-1.19.2
</details>

### Mod Version

1.0.1.b

**Comment by GameOnne** [comment]
There have been no 1.19.2 releases for almost a year now, as a result they're outdated and don't work with Create 0.5.1f (latest version). If you really need it, you can downgrade to Create 0.5.1c.

**Comment by ninjaguardian** [comment]
Ahh. Welp, not much I can do.
